### ISSUE TITLE
Green channel and Red edge channel data

### ISSUE THREAD

**Issue by Addhi86** [inkyusa/weedNet#1]
Hi, can you please provide the Green channel and Red edge channel data?
Also i am just wondering if you the some RGB images of weed and crops?

**Comment by inkyusa** [comment]
Dear Addhi86,
Thank you for your interests to our work.
Since the Green and Red edge images were not used in this paper (also they didn't be aligned meaning that the labels won't match up to these extra channels), it may be difficult to upload. Instead, we uploaded sample RGB files under https://github.com/inkyusa/weedNet/tree/rgb-samples. Hope these data provides a general insight of the farm field where we collected dataset.
Again, these RGB images weren't aligned with the label.
